### PR TITLE
Add Debian files for packaging 

### PR DESCRIPTION
**Pull request by eddybl**
We are building certain Python packages for a long time as Debian packages, but the workflow we used so far needs to change.

So the question is if you want to add these files to upstream. For future releases you would/should update the `debian/changelog` file for the changelog.

If you don't want to maintain this I am fine with that and we would do this only for our version.

### CODE REVIEW

**Comment by Araneidae** [comment]
@AlexanderWells-diamond , any thoughts on this?

**Comment by AlexanderWells-diamond** [comment]
I'm afraid I don't really understand what this PR is trying to achieve. Does Debian need different builds compared to other linux/unix platforms?

**Comment by eddybl** [comment]
This PR would allow epicsdbbuilder to be built and installed using Debian ecosystem. If the above files are present, one is able to use `dpkg-buildpackage` to create a `.deb` package out of the Python source files, so you get something like `python3-epicsdbbuilder.deb` which then you can install via the Debian based package manager ( `apt`). In this case you don't have to rely or even need `pip` or PyPI (which in our case is not available inside our closed accelerator networks).

With more recent Python versions this will become more of an issue, as installing Python packages via `pip` system wide is dis-encouraged ( see [PEP 668](https://peps.python.org/pep-0668/) ) and actually results in an error (which you can override by a command line parameter) for example in Ubuntu 24.04 (LTS).

One "downside" is that the uniqueness of the Debian package is defined by the `debain/changelog` file, so for a new version release, this would need to be updated. To give an example, [here is the changelog file for the debainzed version of numpy](https://salsa.debian.org/python-team/packages/numpy/-/blob/master/debian/changelog?ref_type=heads).

In case you don't want to maintain the Debian flavour (by keeping the `debian/changelog` up to date), we can close thsi PR and we would probably set up a workflow similar to how Debian maintains its Python packages: Maintaining our own "Fork" (technically it will not be a fork), where we maintain the Debian related files in a separate branch

**Comment by Araneidae** [comment]
It looks like we currently don't have a `CHANGELOG.rst` in this project (such as [pythonSoftIOC/CHANGELOG.rst](https://github.com/DiamondLightSource/pythonSoftIOC/blob/master/CHANGELOG.rst).  Would the Debian build process with `debian/changelog` being a soft link to such a file, or would the formatting be incompatible?

**Comment by eddybl** [comment]
There are strict formatting requirements for the `debian/changelog`. Each version has an entry such as this, where the first and last line is "critical" and in between is bascially free form text to list the changes:

```
package (1.1.0) stable; urgency=low

* Change 1
* Change 2

 -- Name <email@address.com>  Tue, 31 Oct 2023 14:26:45 +0100
```

so you cannot just include a .rst file.

I am also considering on creating PRs  to add debian files for:

- pythonSoftIOC
- epicscorelibs
- setuptools_dso
- pyepics
- caproto

**Comment by AlexanderWells-diamond** [comment]
Overall I don't think I'm in favour of this and would prefer it to be maintained in a separate place.

This is largely because I'm not sure I'd ever remember to update such files when doing a release!

**Comment by eddybl** [comment]
Ok, makes sense to me. Then we will set up our internal workflow for this (and maybe try to make it publicly available for those who would be interested)

**Pull request closed without merging**
